### ISSUE TITLE
インポートについて

### ISSUE THREAD

**Issue by c0a2111229** [c0a21088/ProjExD#2]
https://github.com/c0a21088/ProjExD/blob/72eed6c1b7352c4331cbfe72d4853d5ea933224d/ex01/quiz.py#L4
インポートは関数外で行ったほうが綺麗に見えると思います

**Comment by c0a21088** [comment]
ありがとうございます。
quiz()関数を他のコードにimportした際に、そちらのコードでdatetimeのimportをしないといけないため、他のこの関数のimportは関数内ですべきです。他のimportも関数内で使用と思います。
